In [56]:
import numpy as numpy
import pandas as pd
# from ipynb.fs.full.data_preprocess import c_fraud_df
c_fraud_df = pd.read_csv("corrected_names.csv")
from sklearn.preprocessing import OneHotEncoder

In [57]:
c_fraud_df.tail(10)

,Unnamed: 0,Caller Number,Call Time,Call Type,Conversation,Sentiment Analysis
11844,11844,+1-617-557-2713,06:39:16,normal,Us finish blowing my hair. U finish dinner alr...,Neutral
11845,11845,+1-617-912-6296,18:48:30,normal,To we sell it all so we'll have tons if coins....,Positive
11846,11846,+1-503-600-5903,09:41:01,normal,Boy's father is John. When John is the NAME of...,Positive
11847,11847,+1-305-543-1963,11:54:08,Spam,hello sir this is your si bank manager. your b...,Negative
11848,11848,+1-213-510-7639,10:52:13,normal,To way I'm going back there!,Neutral
11849,11849,+1-303-953-1271,12:25:05,normal,Looks like you found something to do other tha...,Positive
11850,11850,+1-305-819-5914,00:05:14,normal,K for wat time ü finish?,Positive
11851,11851,+1-212-271-6786,16:37:00,normal,"Right will do, thanks again for coming out",Positive
11852,11852,+1-512-678-5368,14:12:23,normal,Run b sad.. It's over.. Run the at it already....,Negative
11853,11853,+1-808-946-5691,10:50:35,normal,"I friend, which is best way to avoid missunder...",Positive

In [58]:
c_fraud_df.drop('Unnamed: 0',axis = 1, inplace = True)

In [59]:
c_fraud_df

,Caller Number,Call Time,Call Type,Conversation,Sentiment Analysis
0,+1-602-484-3039,05:06:43,normal,That are you doing?,Neutral
1,+1-703-942-8189,15:08:08,Scam,YOU HAVE WON! Is a valued Vodafone customer ou...,Positive
2,+1-901-383-7693,03:36:17,normal,"K, Met me see.",Positive
3,+1-602-747-4851,10:12:14,normal,"He will, you guns close?",Neutral
4,+1-214-359-8191,09:42:00,normal,Oh oh... Men mud change plan liar... To back h...,Neutral
...,...,...,...,...,...
11849,+1-303-953-1271,12:25:05,normal,Looks like you found something to do other tha...,Positive
11850,+1-305-819-5914,00:05:14,normal,K for wat time ü finish?,Positive
11851,+1-212-271-6786,16:37:00,normal,"Right will do, thanks again for coming out",Positive
11852,+1-512-678-5368,14:12:23,normal,Run b sad.. It's over.. Run the at it already....,Negative
11853,+1-808-946-5691,10:50:35,normal,"I friend, which is best way to avoid missunder...",Positive

In [60]:
array = c_fraud_df["Call Type"].values.reshape(-1,1)
array

array([['normal'],
       ['Scam'],
       ['normal'],
       ...,
       ['normal'],
       ['normal'],
       ['normal']], dtype=object)

In [65]:
encoder = OneHotEncoder()
encoded_values = encoder.fit_transform(array).toarray()
encoded_values

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [69]:
encoded_df = pd.DataFrame(encoded_values, columns=encoder.get_feature_names_out(['Call Type']))
encoded_df = encoded_df.astype(int)
encoded_df

       Call Type_Scam  Call Type_Spam  Call Type_normal
0                   0               0                 1
1                   1               0                 0
2                   0               0                 1
3                   0               0                 1
4                   0               0                 1
...               ...             ...               ...
11849               0               0                 1
11850               0               0                 1
11851               0               0                 1
11852               0               0                 1
11853               0               0                 1

[11854 rows x 3 columns]

In [74]:
final_df = pd.concat([c_fraud_df,encoded_df], axis=1).drop('Call Type', axis = 1)
final_df.head()

,Caller Number,Call Time,Conversation,Sentiment Analysis,Call Type_Scam,Call Type_Spam,Call Type_normal
0,+1-602-484-3039,05:06:43,That are you doing?,Neutral,0,0,1
1,+1-703-942-8189,15:08:08,YOU HAVE WON! Is a valued Vodafone customer ou...,Positive,1,0,0
2,+1-901-383-7693,03:36:17,"K, Met me see.",Positive,0,0,1
3,+1-602-747-4851,10:12:14,"He will, you guns close?",Neutral,0,0,1
4,+1-214-359-8191,09:42:00,Oh oh... Men mud change plan liar... To back h...,Neutral,0,0,1